export {default as Home} from './Home.jsx'
export {default as About} from './About.jsx'
export {default as Product} from './Product.jsx'
export {default as Info} from './info.jsx'
export {default as Page404} from './Page404.jsx'
export {default as Search} from './Search.jsx'